// controllers/videoConferenceController.js
const VideoConferenceRequest = require("../models/VideoConferenceRequest");

exports.createVideoConferenceRequest = async (req, res, next) => {
  try {
    const { name, email, subject, phone } = req.body;

    if (!name || !email || !subject || !phone) {
      return res.status(400).json({ message: "Tous les champs sont requis." });
    }

    // The roomId is automatically generated by the model's default value
    const newRequest = new VideoConferenceRequest({
      name,
      email,
      subject,
      phone,
    });

    const savedRequest = await newRequest.save();

    return res.status(201).json({
      message: "Demande de vidéoconférence créée avec succès.",
      request: savedRequest,
    });
  } catch (error) {
    next(error);
  }
};
